### PR TITLE
623: Prevent duplicate Verify or Upload Jobs from running

### PR DESCRIPTION
**Pull request by mjmeijer**
New Verify or Upload commands cancels all existing Verify and Upload on that project.

### CODE REVIEW

**Comment by jantje** [comment]
@mjmeijer 
I have been thinking hard about this pull request and I came to the conclusion not to accept this pull request.

My arguments not to are:
Taking into account slide after "optimization is the root of all evil" https://speakerdeck.com/player/2fa0e3a6cb3a4397a9794943553f42fc?#
Normally you do not click 50 times a build.
If you click 50 times build you probably want 50 builds done.
Adding a optimisation that cancels the previous build may have averse effect and complicates maintenance/testing work.
So as to me there is no need to optimize; so we shouldn't.

It is a hard call because:
I really appreciate your input/work so I hate to refuse this pull request. 
In the short time you have been around here you have already contributed good things to the plugin.

Best regards
Jantje

**Comment by mjmeijer** [comment]
We can move the nagging Job up one level so it is still called 50 times. If Jobs are longer running you can now clobber the queue, this should be prevented I think. But it is your call.

**Comment by mjmeijer** [comment]
My emphasis will be on making it as easy as possible for people to migrate from Arduino IDE and preventing the usual "first time on Eclipse experience"

**Comment by jantje** [comment]
> My emphasis will be on making it as easy as possible for people to migrate from Arduino IDE and preventing the usual "first time on Eclipse experience"

Sounds like a really good idea. But it is also a good ide to discuss upfront to avoid "frustration".
Is it ok for you if I assign you to issues I think are in this are and the mac related ones.
You can always unassign yourself.
I'm thinking about #80. If I add a "set port to project" you could do the gui (be it in the menu or as a combobox in the toolbar)

**Pull request closed without merging**
