### PR TITLE
upgrade to eclipse 4.5/mars

### PR DESCRIPTION
**Pull request by neuweiler**

### CODE REVIEW

**Comment by jantje** [comment]
Long time no see :-)
I guess this is a fix for #288 
I haven't merged yet because there is a merge conflict and I see "unexpected changes"
The second one is probably due to my lack of understanding this area.
I see you added org.eclipse.m2e.core.maven2Builder and org.eclipse.m2e.core.maven2Nature. As far as I know nothing is wrong with that.
In the file it.baeyens.arduino.parent/pom.xml I had expected additions to "add something to make mars work" but I only see replacements of luna to mars. Does this mean luna will now no longer work? After all the reference to the luna repository has been removed.

**Comment by wimjongman** [comment]
* There is no need to add the maven nature to the project. Although the project contains a pom.xml it is not a true maven project.

* Luna is removed. this should not be done. 

I think we should abandon this patch.

**Comment by jantje** [comment]
Actually I already fixed this in #288 
I didn't add the maven
I have luna and mars
and there was 1 plugin with a explicit version number for which I removed the version number.
Basically this pull request enabled me to fix the issue :-)

**Comment by wimjongman** [comment]
Cool! I saw the patch. Works fine.

**Comment by neuweiler** [comment]
Hi,

Yes.. you're right.. I forgot that Luna would be abandoned.. apologies.

Cheers,
  Michael

**Pull request closed without merging**
