### PR TITLE
New logos

### PR DESCRIPTION
**Pull request by MarceloLimori**
Copyright (c) 2016 Marcelo Limori 
All rights reserved. These images and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which is available at http://www.eclipse.org/legal/epl-v10.html

Contributors:
Marcelo Limori - Creation
I authored 100% of the content
I have the right to contribute the content
I contribute the content under the EPL

### CODE REVIEW

**Comment by jantje** [comment]
cool txs

**Comment by yasriady** [comment]
very nice logo, Limori ...
Hello Jantje, when will you embed the logo into arduino-eclipse plugin? I think this is very nice logo to showing in your plugin ..... well done guys ..

**Comment by jantje** [comment]
@yasriady It already is in the nightly

**Comment by mdilger** [comment]
Hi Guys,

I have just clicked the option to "check for updates" under "help" but no new logo's.  Do I need to do reinstall from the nightly to get the "new look".
Cheers,
Mike

**Comment by jantje** [comment]
When you install from the stable the nightly update site is not "active".
If you want the new logo's just activate/add the nightly update site to the download sites and try again

**Comment by mdilger** [comment]
I checked the application and the nightly update site was activated.  I thought this was the case I have been seeing regular updates to the plugin as I normally check for updates each day.  However the logo's have not changed on my installation yet.

Any ideas?

**Comment by MarceloLimori** [comment]
I works for me. Note that only the icon and banner in the About screen are  
new, the splash should be the old one.

On Wed, 18 May 2016 20:25:26 -0300, mdilger <notifications@github.com>  
wrote:

>
> I checked the application and the nightly update site was activated. I  
> thought this was the case I have been seeing regular updates to the  
> plugin as I >normally check for updates each day. However the logo's  
> have not changed on my installation yet.
>
> Any ideas?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub



-- 
Using Opera's mail client: http://www.opera.com/mail/

**Comment by mdilger** [comment]
Thanks for the feedback.  I may have been fooled by the splash.  I will take another look tonight.

**Comment by jantje** [comment]
In my installation they also reverted back to the old ones :-(
I'm not sure what is going on

**Comment by mdilger** [comment]
At least it is not just me ;-)  I checked again last night and they are definitely still the old logos.

**Comment by jantje** [comment]
I just upgraded again and the logo's are not there.
As you can see in github the icons are correct https://github.com/jantje/arduino-eclipse-plugin/tree/master/it.baeyens.arduino.application/icons
I checked the package it.baeyens.arduino.application on my system. It is dated 20160520 so that should contain the new icons but it does not.
I checked my build server and the master does contain the correct logo's
However I see that my working branch does not contain the latest versions https://github.com/jantje/arduino-eclipse-plugin/tree/working/it.baeyens.arduino.application/icons

As I have http://eclipse.baeyens.it/nightly_jantje as a repository I'm just suffering my lack of knowledge of git(hub)

@mdilger 
Do you have the repository http://eclipse.baeyens.it/nightly_jantje

**Comment by mdilger** [comment]
@jantje 
I did not have that repository set up,but I have just tried it and still no new logo's..

**Comment by jantje** [comment]
@mdilger 
I ment it the other way around. If you had it could explain.
I have been able to sync the github reposotories by now.
I'm investigating

**Comment by jantje** [comment]
Today I upgraded again and the icons are there :-)

**Comment by mdilger** [comment]
@jantje 

Sorry about the dealy, I will take another look tonight.

**Pull request merged**
