### PR TITLE
606: Remove dependency on org.eclipse.wb.core.lib

### PR DESCRIPTION
**Pull request by mjmeijer**
Also remove PDE and JDT dependency, create a target file and change config.ini to put the default workspace in path ~/Documents/sloeber-worksapce as default instead of the invisible and non-selectable application root folder. This must also be best practice on Linux and Windows with multiple users: each user gets his own workspace.

### CODE REVIEW

**Comment by jantje** [comment]
can you remove the conflict?

**Comment by mjmeijer** [comment]
I resolved the conflicts

**Comment by wimjongman** [comment]
I think I already did.⁣

**Comment by wimjongman** [comment]
Please do not remove pde. It is there for the osgi console.⁣

Also jdt is quite handy to have around.

**Comment by wimjongman** [comment]
Ok cool. Thanks Maarten.⁣

**Comment by jantje** [comment]
I actually also wonder whether PDE and JDT are a "must have"

**Comment by wimjongman** [comment]
Yes they are.⁣

**Pull request merged**
