### PR TITLE
#306 Remove the ArduinoIDE dependency

### PR DESCRIPTION
**Pull request by wimjongman**
* Better install progress reporting
* Removed dialog before installing
* Refactored library installation
* New splash

### CODE REVIEW

**Comment by jantje** [comment]
@wimjongman 
Are you sure you rebased before making the pull request?
If I'm not mistaken you are marked as contributor so you do not have to make pull requests ;-)

**Comment by wimjongman** [comment]
I am positive. I used the default formatter but I have redone that. It looks like you are also not using the formatter in the root of the repository.

**Comment by jantje** [comment]
I'm using java conventions build in and format at save time.
It looks like you have a longer line width.

**Comment by wimjongman** [comment]
Yes, I have used the codeformat.xml that is in the root of the repo. Should we remove that file?

**Comment by jantje** [comment]
deleted in the big change branch

**Pull request merged**
