### PR TITLE
Feature/serial monitor

### LINKED ISSUE #142: serial monitor: save linefeed option
Now the serial monitor always reverts to the default (no linefeed) option.
Adding a "last used serial monitor option" would be nice.

### PR DESCRIPTION
**Pull request by rlogiacco**
I should have fixed #142 and a little visualization glitch in the serial monitor view.

I've also changed some constants in `Const` (which I believe were labels): please double check those changes in order to avoid unwanted impacts.

The big change block in `InstancePreferences` is due to source code formatting, the real change in there was some methods being renamed to better respond to the Java naming convention (first char for method and variable names should be lowercase).

### CODE REVIEW

**Comment by jantje** [comment]
the const stuff are keys for the instance scope. They are not visible text. You can see that in the name as it contains KEY.
Const is a really bad name by the way (my bad).
A earlier pull request added Defaults. I think a static singleton Keys class is a good idea.

**Comment by rlogiacco** [comment]
So is it better if I leave their value as they were? What will be the impact on the users if we change those values? I believe they will lose their setting, right?

I will investigate something on that front. Personally I don't like the Constants, Defaults, etc... approach as it tends to be causing merge conflicts (multiple commits manipulating the same file), but I'll have a look and see if there's any better solution.

**Comment by jantje** [comment]
> What will be the impact on the users if we change those values? I believe they will lose their setting, right?

Yes but in this case it is "the last used settings" so it will forget what was used last time. I personally prefer not to touch them, but then I'm not sensitive to spelling mistakes.

**Comment by rlogiacco** [comment]
What if I go once over them all and change them so they are no more affected by spelling? :smile:

In Java it's an established practice to use something like `settings.lastUsed.boardsFile` or `settings.boards.lastUsedFile`. 

That should also cover us towards future contributors which might find those values confusing in terms of common practices.

The counterside is they will all change, but at least they will change all at once.

**Pull request merged**
