### PR TITLE
#334 upgrade to java 8

### PR DESCRIPTION
**Pull request by wimjongman**
* Upgraded Tycho to 0.24
* Instructed Tycho to use java 8 instead of 7

### CODE REVIEW

**Comment by jantje** [comment]
@wimjongman 
Seems this one fails

>PID=2075 still running at 180 seconds

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-publisher-plugin:0.24.0:publish-products (default-publish-products) on project it.baeyens.arduino.product: Detected Luna or older launcher feature org.eclipse.equinox.executable version 3.6.102.v20150204-1316.

[ERROR] Native product launchers for MacOSX can only be built against Eclipse Mars or newer.

[ERROR] To fix this, you can either build against Eclipse Mars or newer (recommended) or go back to Tycho <= 0.22.0

**Comment by wimjongman** [comment]
Yes I looked into it. It seems Travis is building against kepler.

**Comment by jantje** [comment]
it says so here
https://github.com/jantje/arduino-eclipse-plugin/blob/master/.travis.yml
Time for a change?

**Comment by wimjongman** [comment]
Most certainly, I will add this to my pull request so that we can see the
effect.

**Comment by wimjongman** [comment]
Yes that fixed it. It now builds on Java 8.

**Pull request merged**
