### PR TITLE
Fix for second part of #408 (hardware libs overriding private ones)

### PR DESCRIPTION
**Pull request by nafep**
#### The context

Two issues have been described in #408, the first being solved with #425.
This PR addresses the second one:

> The problem is that the names of the include files are the same as in the "stock" libraries, so the plugin "helps" me adding the default libraries to my project which I have to avoid.

#### The issue

However, unless I did not get the point, @jantje 's suggested fix to
> use the import source code for that. Use another folder then libraries as that folder is maintained by the plugin.

did not work for me. Indeed, regardless the name of the additional folder name, the plugin would always take the "hardware library" when two homonymous libraries appear in the private and the hardware libraries. This is due to the way the HashMap is built in `it.baeyens.arduino.tools.Libraries.getAllInstalledLibraries()`.

#### The proposed solution

I assume that if you include a private library with the same name as a hardware one, your intention is probably to use the private one rather than the "official" hardware one. 
Therefore, I propose to change the order the HashMap in `it.baeyens.arduino.tools.Libraries.getAllInstalledLibraries()` is built accordingly.
However, I have also added a preference setting that allows to toggle this behaviour from "hardware library priority" to "private library priority" to accommodate for other possible needs.

### CODE REVIEW

**Comment by jantje** [comment]
I will not accept this pull request.
The correct sequence of selection is 1 hardware libraries, private libraries, generic libraries.

**Comment by nafep** [comment]
OK. I must admit that, although the proposed change seems to work for me, I was not too sure that it would be the right fix. Neither do I know if I have followed the right "workflow" to make my proposal; if it followd the usual practice for open source projects. (Maybe I should have discussed my idea before submitting in the #408 thread?) My motivation was to make a concrete proposal rather than expecting/waiting for someone else to spend time on it.

From a practical point of view: 
1) is there something I can/should do with respect to my PR? May a change in my proposal make it acceptable or should I forget this approach completely? I'd be grateful for any hint.
2) I've been fiddling around quite a bit, but without my "fix", I am not able to build any ESP8266 project using a locally modified version of the ESP8266WebServer library. If my proposal is to be trashed (no bad feeling about that ;-), should I reopen a new specific issue (although #408 is already partially addressing it) or is there something else to do?

Thanks in advance for your time and efforts.

**Comment by rlogiacco** [comment]
Hi @nafep, if I understand @jantje's comment, he is willing to accept a slightly different solution which does not override hardware libraries, but permit overriding of general libraries.
In the former category fall all libraries included in the `platform` selection, in the latter those obtained via the `library manager`. 
If my understanding is correct he is suggesting to place private libraries in the middle and let platform libraries untouched and non _overridable_.

**Comment by nafep** [comment]
Thanks @rlogiacco for your suggestion. However, as far as my understanding goes, most ESP8266 libraries, and incidentally the `ESP8266WebServer` library I'm concerned with, are part of the **hardware** libraries, so the proposed order would not help. Besides, I'm afraid the order in @jantje's answer is not a suggestion but the currently implemented one...

**Comment by jantje** [comment]
>Besides, I'm afraid the order in @jantje's answer is not a suggestion but the currently implemented one...

This is correct. The reason is that hardware libraries are the first to be picked is that hardware providers give the correct libraries to work with their hardware. Think about SPI. 
Again you should look at import source code. That should work for you. Otherwise consider deleting the hardware folder or adding a #ifdef or renaming your library.

**Comment by nafep** [comment]
I was taking the "import source code" feature the wrong way. Got it to work finally, almost as conveniently as I wanted it to be ;-) Thanks again for your support!

**Comment by jantje** [comment]
Exactly as I though :-)
Txs for the other pull requests and hope to see you again.

**Pull request closed without merging**
